// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7r7WS-_mh6pQ22_5MigEKBE82JRpISTE',
    appId: '1:816159040397:android:b62f2fffb7b7b1a7fb93c4',
    messagingSenderId: '816159040397',
    projectId: 'neobisflutterauth',
    storageBucket: 'neobisflutterauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8b1xuYLANiUAN-St6kdiQCEiJ6fxaIm8',
    appId: '1:816159040397:ios:2b1af3e7b1e76eb8fb93c4',
    messagingSenderId: '816159040397',
    projectId: 'neobisflutterauth',
    storageBucket: 'neobisflutterauth.appspot.com',
    iosBundleId: 'com.example.neobisFlutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBenPIbGfiBfhRjvlq8SuXZEvaoFRYEfUc',
    appId: '1:816159040397:web:43d1d9ffb2f3e98cfb93c4',
    messagingSenderId: '816159040397',
    projectId: 'neobisflutterauth',
    authDomain: 'neobisflutterauth.firebaseapp.com',
    storageBucket: 'neobisflutterauth.appspot.com',
    measurementId: 'G-35LPD3JNM7',
  );
}
